#!/bin/bash -l                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                               
# Peter L. Morrell - 11 April 2024 - Falcon Heights, MN                                                                                                                                                                                        
                                                                                                                                                                                                                                               
set -e                                                                                                                                                                                                                                         
set -o pipefail                                                                                                                                                                                                                                
                                                                                                                                                                                                                                               
# Usage: Provide a list of SNP positions in the form chromsome:position 
# (e.g, Vu01:20060064). The other required input is the named of a VCF file 
# indexed by bcftools. The current version of the script is designed to report
# all individuals with the alternate allele in the homozygous or heterozygous 
# state. (We need to change the awk line to '/0\/0' ).                                                                                                                                                                                                                            
                                                                                                                                                                                                                                               
module load bcftools/1.16-gcc-8.2.0-5d4xg4y                                                                                                                                                                                                    
                                                                                                                                                                                                                                               
readarray -t SNP_POS < $1                                                                                                                                                                                                                                     
VCF=$2                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                               
printf '%s\n' "${SNP_POS[@]}"                                                                                                                                                                                                              
                                                                                                                                                                                                                                               
for i in "${SNP_POS[@]}"                                                                                                                                                                                                                  
    do                                                                                                                                                                                                                       
    bcftools view -r "$i" "$VCF" |                                                                                                                                                                                                  
    bcftools query -f '[%CHROM\t%POS\t%ID\t%SAMPLE\t%GT\n]' |                                                                                                                                                                     
    awk -v FS='\t' -v OFS='\t' '/0\/1|1\/1/ {print $1, $2, $3, $4}'                                                                                                                                                                                                      
    done
